services:
  postgres:
    build: ./postgres
    container_name: algalog-postgres
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "4"
        max-size: "40m"
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: /opt/volumes/algalog/postgres/db
        target: /var/lib/postgresql/data
    env_file: ./postgres/postgres.env
    networks:
      - algalog-network
        
networks:
  algalog-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.200.0.0/16"